base_config:
  - configs/tts/lj/fs2.yaml

max_frames: 8000
audio_sample_rate: 24000
hop_size: 128            # Hop size.
fft_size: 512           # FFT size.
win_size: 512           # FFT size.
fmin: 30
fmax: 12000
min_level_db: -120

binary_data_dir: 'data/binary/ritsu-24k-midi-dp'

pitch_type: frame
task_cls: tasks.tts.pe.PitchExtractionTask
pitch_extractor_conv_layers: 2


# config for experiments
max_tokens: 20000
use_spk_embed: false
num_valid_plots: 10
max_updates: 60000

num_test_samples: 0
test_ids: []

# test_ids: [ 68, 70, 74, 87, 110, 172, 190, 215, 231, 294,
#             316, 324, 402, 422, 485, 500, 505, 508, 509, 519 ]
# use_energy_embed: false
# test_num: 523
# valid_num: 348
